export { default as MainRouter } from './Routers/MainRouter';
export { default as Footer } from './Home/Footer';
export { default as NavBar } from './Home/NavBar';
export { default as Entry } from './Home/Entry';
export { default as Home } from './Home/Home';
export {default as CommentTable} from './DashBoard/Comments/CommentTable';
export {default as TablesView} from './DashBoard/Comments/TablesView';
export {default as CoursesDashBoard} from './DashBoard/Courses/CoursesDashBoard.jsx';
export { default as CoursesView } from './Courses/CoursesView';
export { default as CourseViewDetails } from './Courses/CourseViewDetails';